# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: run-tests
#   namespace: flux-system
# spec:
#   template:
#     spec:
#       containers:
#       - name: run-tests
#         image: perl:5.34.0
#         command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
#       restartPolicy: Never
#   backoffLimit: 4
  
apiVersion: batch/v1
kind: Job
metadata:
  name: github-action-trigger
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: github-action-trigger-container
        image: byrnedo/alpine-curl:latest  # Using a container with curl pre-installed
        envFrom:
        - secretRef:
            name: github-token
        command: ["sh", "-c"]
        args:
        - |
          apk --upgrade add curl;
          echo $token;
          curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $token" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/chezka-gaddi/node-app/dispatches \
                -d '{"event_type": "run_test", "client_payload": {"key": "Completed running the test!!"}}';
      restartPolicy: Never


# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: github-action-trigger
#   namespace: flux-system
# spec:
#   template:
#     spec:
#       containers:
#       - name: github-action-trigger-container
#         image: alpine:latest
#         volumeMounts:
#           - name: github-secret-volume
#             mountPath: /etc/secret-volume
#             readOnly: true
#         command: ["sh", "-c"]
#         args:
#           - |
#             apk --upgrade add curl;
#             ACCESS_TOKEN=$(cat /etc/secret-volume/token);
#             curl -X POST -H "Content-Type: application/json" https://api.restful-api.dev/objects -d '{"name": "Chez", "data": {"year": 1994, "test": $ACCESS_TOKEN}}';
#       restartPolicy: Never
#       volumes:
#         - name: github-secret-volume
#           secret:
#             secretName: github-token