apiVersion: batch/v1
kind: Job
metadata:
  name: no-secrets
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: no-secrets-container
        image: byrnedo/alpine-curl:latest  # Using a container with curl pre-installed
        command: ["sh", "-c"]
        args:
        - |
          curl -X POST -H "Content-Type: application/json" https://api.restful-api.dev/objects -d '{"name": "Chez", "data": {"name": "name"}}';
      restartPolicy: Never