apiVersion: batch/v1
kind: Job
metadata:
  name: github-action-trigger
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: github-action-trigger-container
          image: curlimages/curl:latest  # Using a container with curl pre-installed
          command: ["sh", "-c"]
          args:
            - |
              curl -X POST -H "Content-Type: application/json" https://api.restful-api.dev/objects -d '{"name": "Chez", "data": {"year": 1994, "info": ${token}}}'
          envFrom:
            - secretRef:
                name: test
      restartPolicy: Never