apiVersion: batch/v1
kind: Job
metadata:
  name: run-tests
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: run-tests
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(8000)"]
      restartPolicy: Never
  backoffLimit: 4
apiVersion: batch/v1
