apiVersion: batch/v1
kind: Job
metadata:
  name: github-action
  namespace: static-sample
spec:
  template:
    spec:
      containers:
      - name: github-action-container
        image: byrnedo/alpine-curl:latest  # Using a container with curl pre-installed
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - secretRef:
            name: github-token
        command: ["sh", "-c"]
        args:
        - |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${token}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/chezka-gaddi/node-app/dispatches \
          -d '{"event_type": "run_test", "client_payload": {"key": "Finally got this test working!!", "env": "'$POD_NAMESPACE'"}}';
      restartPolicy: Never