---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-sample1
  namespace: static-sample
spec:
  replicas: 5
  selector:
    matchLabels:
      app: static-sample
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: static-sample
    spec:
      containers:
        - image: cgaddi/node-app:1.1.6
          imagePullPolicy: IfNotPresent
          name: static-sample
