apiVersion: flagger.app/v1beta1
kind: AlertProvider
metadata:
  name: slack-bot-alert
  namespace: flux-system
spec:
  type: slack
  channel: general
  username: flagger
  # webhook address (ignored if secretRef is specified)
  address: https://slack.com/api/chat.postMessage
  # optional http/s proxy
  # proxy: http://my-http-proxy.com
  # secret containing the webhook address (optional)
  secretRef:
    name: slack-bot-token
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: on-call-url
#   namespace: flagger
# data:
#   address: <encoded-url>
#   token: slack-bot-token