---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-sample
  namespace: static-sample
spec:
  replicas: 10
  selector:
    matchLabels:
      app: static-sample
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: static-sample
    spec:
      containers:
        - image: nigelpoulton/k8sbook:1.0
          imagePullPolicy: IfNotPresent
          name: static-sample
