---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# metadata:
#   name: backend
#   namespace: default
# spec:
#   interval: 5m
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: webapp
#   healthChecks:
#     - apiVersion: apps/v1
#       kind: Deployment
#       name: backend
#       namespace: dev
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - github.yaml
