---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-post-deploy
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./clusters/lab/post-deploy/"
  interval: 60m
  timeout: 5m
  prune: true
  wait: true
  force: true